### ISSUE TITLE
url to wdio portal using axios

### ISSUE THREAD

**Issue by zabakala** [BorisOsipov/reportportal-js-client#16]
Hello. I am using wdio-reportportal-reporter and whenever it tries to fire a request, it always says:

```
wdio-reportportal-reporter: Error: Request failed with status code 500: {"timestamp":1593297679633,"status":500,"error":"Internal Server Error","message":"The request was rejected because the URL contained a potentially malicious String \"//\"","path":"/v1//launch"}
    at axios.then.catch (...\node_modules\reportportal-js-client\lib\rest.js:33:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Apparently the part between v1 and launch is empty evenf if the config is properly defined:

```
token: '...',
endpoint: '.../api/v1',
launch: 'foo',
```

it appears to be a buggy behavior (?)

**Comment by BorisOsipov** [comment]
Which wdio-reporter version do you use? Is it reproduced in latest?
